/* UniServe client: Supabase Auth + Row Level Security protect all data. */
const cfg = window.UNISERVE_CONFIG || {};
const configured = cfg.supabaseUrl && !cfg.supabaseUrl.includes('YOUR_PROJECT') && cfg.supabaseAnonKey && !cfg.supabaseAnonKey.includes('YOUR_');
const db = configured ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const app = document.querySelector('#app');
let session = null, profile = null, requests = [], activeView = 'dashboard';

const escape = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pretty = v => (v || '').replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
const date = v => new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(v));
const statusClass = s => `tag ${s || 'pending'}`;

function shell(content) {
  app.innerHTML = `<div class="layout"><aside><a class="brand" href="#"><span>U</span>UniServe</a><p class="eyebrow">STUDENT SERVICES</p>
  <nav><button data-view="dashboard">Overview</button><button data-view="new-request">New request</button><button data-view="requests">My requests</button>${['staff','admin'].includes(profile?.role) ? '<button data-view="queue">Service queue</button>' : ''}${profile?.role === 'admin' ? '<button data-view="approvals">Approvals</button><button data-view="reports">Reports</button>' : ''}</nav>
  <div class="account"><div class="avatar">${escape((profile?.full_name || 'U')[0])}</div><div><strong>${escape(profile?.full_name || 'Demo student')}</strong><small>${pretty(profile?.role || 'student')}</small></div><button class="text" id="signout">Sign out</button></div></aside>
  <section class="content"><header><div><p class="eyebrow">${date(new Date())}</p><h1>${activeView === 'dashboard' ? 'Good day.' : pretty(activeView)}</h1></div><button class="mobile-menu" aria-label="Open navigation">☰</button></header>${content}</section></div>`;
  document.querySelectorAll('[data-view]').forEach(b => b.onclick = () => { activeView = b.dataset.view; render(); });
  document.querySelector('#signout').onclick = signOut;
}

function authPage(message = '') {
  app.innerHTML = `<div class="auth"><section><a class="brand" href="#"><span>U</span>UniServe</a><p class="eyebrow">UNIVERSITY STUDENT SERVICES</p><h1>Requests, without the runaround.</h1><p>Submit a concern to the right office and track every step in one place.</p><div class="notice">${configured ? 'Sign in with your university account.' : 'Demo mode is active. Add Supabase credentials in <code>config.js</code> to connect your project.'}</div></section><form id="auth-form" class="card"><h2>Welcome back</h2><p class="muted">Use your university email to continue.</p>${message ? `<p class="error">${escape(message)}</p>` : ''}<label>Email<input required type="email" name="email" placeholder="example@gmail.com"></label><label>Password<input required type="password" name="password" minlength="6" placeholder="••••••••"></label><button class="primary">Sign in</button><button type="button" id="signup" class="text">New here? Create an account</button></form></div>`;
  document.querySelector('#auth-form').onsubmit = signIn;
  document.querySelector('#signup').onclick = signUp;
}

function authError(error) {
  const code = error?.code ? ` (${error.code})` : '';
  if (error?.code === 'anonymous_provider_disabled') return `This page is receiving an anonymous sign-in error${code}, but UniServe uses email/password only. Close other Supabase tabs, then hard-refresh this page (Ctrl+F5). Verify you opened this project's index.html.`;
  if (error?.code === 'email_provider_disabled') return `Email/password sign-in is disabled in Supabase${code}. Enable Authentication > Providers > Email.`;
  if (error?.code === 'signup_disabled') return `New registrations are disabled in Supabase${code}. Enable Allow new users to sign up in Authentication > Providers > Email.`;
  return `${error?.message || 'Authentication failed.'}${code}`;
}
async function signIn(e) { e.preventDefault(); const f = new FormData(e.currentTarget); if (!configured) { session = { user: { id: 'demo-user' } }; profile = { full_name: 'Alex Santos', role: 'student' }; requests = demoRequests(); render(); return; } const { error } = await db.auth.signInWithPassword({ email: f.get('email'), password: f.get('password') }); if (error) authPage(authError(error)); }
async function signUp() { if (!configured) return authPage('Demo mode does not create accounts. Configure Supabase to enable registration.'); const form = document.querySelector('#auth-form'); if (!form.reportValidity()) return; const email = document.querySelector('[name=email]').value.trim(), password = document.querySelector('[name=password]').value; const { error } = await db.auth.signUp({ email, password, options: { data: { full_name: email.split('@')[0] } } }); authPage(error ? authError(error) : 'Check your email to confirm your account.'); }
async function signOut() { if (configured) await db.auth.signOut(); session = profile = null; requests = []; authPage(); }

function dashboard() { const open = requests.filter(r => !['completed','rejected','cancelled'].includes(r.status)); const done = requests.filter(r => r.status === 'completed'); return `<div class="stats"><article><small>Open requests</small><strong>${open.length}</strong><span>In progress or awaiting review</span></article><article><small>Completed</small><strong>${done.length}</strong><span>Requests successfully closed</span></article><article><small>Average response</small><strong>2.4d</strong><span>Based on completed requests</span></article></div><div class="split"><section class="card"><div class="row"><div><p class="eyebrow">RECENT ACTIVITY</p><h2>Your requests</h2></div><button class="text" data-view="requests">View all →</button></div>${requestTable(requests.slice(0, 4))}</section><aside class="help"><p class="eyebrow">NEED HELP?</p><h2>Not sure where to start?</h2><p>Describe your concern and we’ll route it to the appropriate service unit.</p><button class="primary" data-view="new-request">Start a request</button></aside></div>`; }
function requestTable(items) { if (!items.length) return '<div class="empty">No requests yet. Create your first request to get started.</div>'; return `<div class="request-list">${items.map(r => `<button class="request" data-detail="${r.id}"><span><strong>${escape(r.reference_no)}</strong><small>${escape(r.service_type)} · ${date(r.created_at)}</small></span><span class="${statusClass(r.status)}">${pretty(r.status)}</span><span>›</span></button>`).join('')}</div>`; }
function newRequest() { return `<form id="request-form" class="card form"><p class="eyebrow">SERVICE REQUEST</p><h2>Tell us what you need</h2><p class="muted">Fields marked with * are required. You will receive a reference number after submission.</p><div class="grid"><label>Service type *<select required name="service_type"><option value="">Select a service</option><option>Certification / Document Request</option><option>Clearance</option><option>Enrollment Assistance</option><option>Student Information Correction</option><option>Academic Concern</option><option>Other</option></select></label><label>Priority *<select required name="priority"><option value="normal">Normal</option><option value="high">High - time-sensitive</option><option value="urgent">Urgent - immediate impact</option></select></label></div><label>Subject *<input required name="subject" maxlength="120" placeholder="Briefly describe your request"></label><label>Description *<textarea required name="description" minlength="15" maxlength="2000" placeholder="Include relevant dates, details, and the outcome you need."></textarea></label><label>Supporting document <input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png" /><small>PDF, JPG, or PNG; maximum 5 MB.</small></label><div class="actions"><button class="primary">Submit request</button><button type="button" class="secondary" data-view="dashboard">Cancel</button></div></form>`; }
function myRequests() { return `<section class="card"><div class="row"><div><p class="eyebrow">REQUEST HISTORY</p><h2>All requests</h2></div><button class="primary" data-view="new-request">+ New request</button></div>${requestTable(requests)}</section>`; }
function queue() { const mine = profile.role === 'staff' ? requests.filter(r => r.assigned_to === profile.id || !r.assigned_to) : requests; return `<section class="card"><p class="eyebrow">SERVICE UNIT</p><h2>Request queue</h2><p class="muted">Evaluate, assign, and update requests. All changes are saved to the request timeline.</p>${requestTable(mine)}</section>`; }
function approvals() { const pending = requests.filter(r => r.status === 'pending'); return `<section class="card"><div class="row"><div><p class="eyebrow">ADMIN REVIEW</p><h2>Approval dashboard</h2><p class="muted">Review newly submitted requests before they enter the service queue.</p></div><span class="tag">${pending.length} awaiting review</span></div>${pending.length ? `<div class="approval-list">${pending.map(r => `<article class="approval"><div><span class="${statusClass(r.priority === 'urgent' ? 'rejected' : 'pending')}">${pretty(r.priority)} priority</span><h3>${escape(r.subject)}</h3><p class="muted">${escape(r.reference_no)} · ${escape(r.service_type)} · ${date(r.created_at)}</p><p>${escape(r.description)}</p></div><div class="approval-actions"><button class="primary" data-approve="${r.id}">Approve</button><button class="secondary" data-reject="${r.id}">Reject</button><button class="text" data-detail="${r.id}">View details</button></div></article>`).join('')}</div>` : '<div class="empty">All caught up. There are no requests awaiting approval.</div>'}</section>`; }
function reports() { const groups = Object.entries(requests.reduce((a,r) => { a[r.service_type] = (a[r.service_type] || 0) + 1; return a; }, {})); return `<div class="stats"><article><small>Total received</small><strong>${requests.length}</strong><span>All time</span></article><article><small>Completion rate</small><strong>${requests.length ? Math.round(requests.filter(r=>r.status==='completed').length / requests.length * 100) : 0}%</strong><span>Completed requests</span></article><article><small>Awaiting action</small><strong>${requests.filter(r=>r.status==='pending').length}</strong><span>Pending evaluation</span></article></div><section class="card"><p class="eyebrow">REQUEST VOLUME</p><h2>Requests by service</h2><div class="bars">${groups.map(([name,count]) => `<div><span>${escape(name)}</span><i style="width:${Math.max(12, count / Math.max(...groups.map(x=>x[1])) * 100)}%"></i><strong>${count}</strong></div>`).join('') || '<p class="muted">No service data yet.</p>'}</div></section>`; }
function detail(id) { const r = requests.find(x => x.id === id); if (!r) return; const canManage = ['staff','admin'].includes(profile.role); shell(`<button class="back" data-view="${canManage ? 'queue' : 'requests'}">← Back to requests</button><section class="card detail"><div class="row"><div><p class="eyebrow">${escape(r.reference_no)}</p><h2>${escape(r.subject)}</h2><p class="muted">${escape(r.service_type)} · submitted ${date(r.created_at)}</p></div><span class="${statusClass(r.status)}">${pretty(r.status)}</span></div><hr><h3>Request details</h3><p>${escape(r.description)}</p><h3>Activity</h3><ol class="timeline">${(r.request_updates || [{status:r.status, note:'Request submitted.', created_at:r.created_at}]).map(u=>`<li><span></span><div><strong>${pretty(u.status)}</strong><p>${escape(u.note || 'Status updated')}</p><small>${date(u.created_at)}</small></div></li>`).join('')}</ol>${canManage ? `<form id="update-form" class="update"><h3>Update request</h3><div class="grid"><label>Status<select name="status">${['pending','processing','on_hold','completed','rejected'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Update note<textarea name="note" required minlength="5" placeholder="Explain this update to the student."></textarea></label></div><button class="primary">Save update</button></form>` : ''}</section>`); document.querySelectorAll('[data-view]').forEach(b => b.onclick = () => {activeView=b.dataset.view;render();}); if (canManage) document.querySelector('#update-form').onsubmit = e => updateRequest(e, r.id); }
async function createRequest(e) { e.preventDefault(); const f = new FormData(e.currentTarget); const payload = { student_id: session.user.id, service_type:f.get('service_type'), priority:f.get('priority'), subject:f.get('subject'), description:f.get('description') }; if (!configured) { payload.id = crypto.randomUUID(); payload.reference_no = `USR-${String(requests.length+101).padStart(5,'0')}`; payload.status='pending'; payload.created_at=new Date().toISOString(); payload.request_updates=[]; requests.unshift(payload); activeView='requests'; render(); return; } const file=f.get('attachment'); if (file?.size) { if (file.size>5_000_000) return alert('Attachment must be 5 MB or smaller.'); const path=`${session.user.id}/${crypto.randomUUID()}-${file.name}`; const {error}=await db.storage.from('request-attachments').upload(path,file); if(error)return alert(error.message); payload.attachment_path=path; } const {error}=await db.from('service_requests').insert(payload); if(error)return alert(error.message); activeView='requests'; await load(); }
async function setApproval(id, approved) { const status = approved ? 'processing' : 'rejected'; const note = approved ? 'Request approved and forwarded to the service queue.' : window.prompt('Reason for rejection (shown to the student):'); if (!note) return; if (!configured) { const r=requests.find(x=>x.id===id); r.status=status; r.request_updates.push({status,note,created_at:new Date().toISOString()}); render(); return; } const {error: updateError}=await db.from('request_updates').insert({request_id:id,status,note,updated_by:session.user.id}); if(updateError)return alert(updateError.message); const {error}=await db.from('service_requests').update({status}).eq('id',id); if(error)return alert(error.message); await load(); }
async function updateRequest(e,id) { e.preventDefault(); const f=new FormData(e.currentTarget), status=f.get('status'), note=f.get('note'); if(!configured){const r=requests.find(x=>x.id===id);r.status=status;r.request_updates.push({status,note,created_at:new Date().toISOString()});detail(id);return;} const {error}=await db.from('request_updates').insert({request_id:id,status,note,updated_by:session.user.id}); if(error)return alert(error.message); await db.from('service_requests').update({status}).eq('id',id); await load(); detail(id); }
function wire() { document.querySelectorAll('[data-view]').forEach(b => b.onclick=()=>{activeView=b.dataset.view;render();}); document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail)); document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>setApproval(b.dataset.approve,true)); document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>setApproval(b.dataset.reject,false)); const f=document.querySelector('#request-form');if(f)f.onsubmit=createRequest; }
function render() { let page = activeView==='dashboard'?dashboard():activeView==='new-request'?newRequest():activeView==='requests'?myRequests():activeView==='queue'?queue():activeView==='approvals'?approvals():reports(); shell(page); wire(); }
async function load() { if(!configured) return render(); const [{data:p},{data:r,error}] = await Promise.all([db.from('profiles').select('*').eq('id',session.user.id).single(),db.from('service_requests').select('*,request_updates(*)').order('created_at',{ascending:false})]); if(error)return alert(error.message); profile=p; requests=r; render(); }
function demoRequests() { const now=new Date().toISOString();return [{id:'1',reference_no:'USR-00101',service_type:'Certification / Document Request',subject:'Request for certificate of enrollment',description:'I need a certificate of enrollment for my scholarship application.',status:'processing',priority:'normal',created_at:now,request_updates:[{status:'pending',note:'Request submitted.',created_at:now},{status:'processing',note:'Your request is being verified by the Registrar.',created_at:now}]},{id:'2',reference_no:'USR-00102',service_type:'Student Information Correction',subject:'Correct middle name',description:'Please update the middle name shown on my student record.',status:'completed',priority:'normal',created_at:now,request_updates:[]}]; }
async function init() { if(!configured)return authPage(); const {data}=await db.auth.getSession(); session=data.session; if(session) await load(); else authPage(); db.auth.onAuthStateChange((_e,s)=>{session=s;if(s)load();else authPage();}); }
init();
